---
abstract: 'Acmeist PEG Parsing Framework'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Pegex
name: Pegex
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
recommends:
  YAML::XS: 0
requires:
  perl: 5.10.0
resources:
  homepage: https://github.com/ingydotnet/pegex-pm/tree
  license: http://dev.perl.org/licenses/
  repository:
    type: git
    url: git://github.com/ingydotnet/pegex-pm.git
    web: https://github.com/ingydotnet/pegex-pm/tree
version: 0.21
